spring.application.name: spring-cloud-gateway
server.port: 8888

eureka.client.serviceUrl.defaultZone: http://localhost:8000/eureka/

# 网关配置
spring:
  cloud:
    gateway:
      routes:
        # 路由到示例项目的spring-cloud-producer模块
      - id: hello_route
        uri: http://localhost:9000
        predicates:
        - Path=/producer/**
        filters:
        - StripPrefix=1
        # 集成eureka注册中心的配置示例
      - id: hello_ribbon_route
        uri: lb://spring-cloud-producer
        predicates:
        - Path=/producerInEureka/**
        filters:
        - StripPrefix=1
        # 路由到百度页面
      - id: baidu_route
        uri: http://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
        - StripPrefix=1
