spring.application.name: spring-cloud-gateway
server.port: 8888

eureka.client.serviceUrl.defaultZone: http://localhost:8000/eureka/

# 网关配置
spring:
  cloud:
    gateway:
      routes:
        # 匹配指定路径的路由
      - id: path_route
        uri: http://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
        - StripPrefix=1
        # 匹配指定cookie的路由
      - id: cookie_route
        uri: http://www.taobao.com
        predicates:
        - Cookie=chocolate, value
        # 匹配指定请求头的路由
      - id: header_route
        uri: http://www.jd.com/
        predicates:
        - Header=X-Request-Id, \d+
        # 匹配指定请求参数的路由
      - id: param_route
        uri: http://tmall.com/
        predicates:
        - Query=param1,value
        # 匹配指定请求参数和请求头的路由
      - id: compose_route
        uri: http://www.oschina.net/
        predicates:
        - Query=param2
        - Header=Header-Route,value